### ISSUE TITLE
Could you please upload the pretrained model on Google Drive?

### ISSUE THREAD

**Issue by dedoogong** [Lausannen/NAS-FCOS#3]
Thank you for sharing your great works!

I'm trying hard but I think it's maybe impossible to download it from Baidu for non-china people as it's so hard to make even just an account for that site. 
So, please I would like to ask you to share the pretrained model on dropbox or google drive. 

Thank you so much!

**Comment by Lausannen** [comment]
We will provide the pretrained models on google drive by tomorrow at the latest so you can download them. After updated, I will remind you it under this issue. Thank you for your suggestion !

**Comment by Lausannen** [comment]
@dedoogong  We have provided another access to our pretrained models. You can find their links in README.md. Due to upload limit, we choose MEGA as cloud drive. If you meet any problems in downloading, please let us know. Thank you !
