### ISSUE TITLE
The trained model you provided is NAS FPN model, not NAS FPN + head model

### ISSUE THREAD

**Issue by iimmortall** [Lausannen/NAS-FCOS#5]
Hi，  I found the trained model you provided (R_50_NAS) is NAS FPN model, not NAS FPN + head model.  In the paper,  you say "It turns out that our NAS-FCOS model still achieves better performance (AP = 38.9 with FPN search only, and AP = 39.8 with both FPN and Head searched) than the DeformFPN-FCOS model (AP = 38.4) under this circumstance."  So, the R_50_NAS is NAS FCOS of FPN search only?

**Comment by Lausannen** [comment]
@iimmortall Sorry for the late reply, we will update the code with head part and upload the pretrained model as soon as possible.
